<?php

use Core\Application;
use Core\Support\Facade;
use Dotenv\Dotenv;

require_once __DIR__ . '/../vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| The first thing we will do is create a new Bault application instance
| which serves as the "glue" for all the components of Bault, and is
| the IoC container for the system binding all of the various parts.
|
*/

$app = new Application(
    realpath(__DIR__ . '/../'),
);

/*
|--------------------------------------------------------------------------
| Load Environment Variables
|--------------------------------------------------------------------------
|
| Load environment variables from the .env file in the project root.
| This is done once at the beginning of the bootstrap process.
|
*/
$dotenv = Dotenv::createImmutable($app->basePath());
$dotenv->safeLoad();

Facade::setFacadeApplication($app);

$cachedServicesPath = $app->bootstrapPath('cache/services.php');

if (file_exists($cachedServicesPath)) {
    /*
    |--------------------------------------------------------------------------
    | Load Cached Service Providers (Production)
    |--------------------------------------------------------------------------
    |
    | For maximum performance, we can cache the entire list of service
    | providers. This file is generated by the `bootstrap:cache` command.
    |
    */
    $providers = require $cachedServicesPath;
    foreach ($providers as $provider) {
        $app->register($provider);
    }
} else {
    /*
    |--------------------------------------------------------------------------
    | Register Service Providers (Development)
    |--------------------------------------------------------------------------
    |
    | In development, we load providers dynamically. This allows for easier
    | debugging and adding new providers without clearing caches.
    |
    */
    // Register ConfigServiceProvider first to make the 'config' service available.
    $app->register(\App\Providers\ConfigServiceProvider::class);

    // Now, register all other providers listed in the configuration.
    $providers = $app->make('config')->get('app.providers', []);
    foreach ($providers as $provider) {
        $app->register($provider);
    }

    // Discover and register Module Service Providers
    $moduleJsonPaths = glob($app->basePath('Modules/*/module.json'));

    if ($moduleJsonPaths === false) {
        $moduleJsonPaths = [];
    }

    foreach ($moduleJsonPaths as $path) {
        $data = json_decode(file_get_contents($path), true);
        if (!empty($data['name']) && !empty($data['enabled']) && $data['enabled'] === true) {
            // A module can have multiple providers listed in its manifest.
            foreach ($data['providers'] ?? [] as $providerClass) {
                if (class_exists($providerClass)) {
                    $app->register($providerClass);
                }
            }
        }
    }
}

return $app;
