version: "3"

# Cấu hình RPC chung cho RoadRunner
rpc:
  # Thêm 'metrics' vào danh sách các service lắng nghe RPC
  listen: tcp://127.0.0.1:6001, tcp://127.0.0.1:6002

# Cấu hình plugin Metrics
metrics:
  # Địa chỉ mà Prometheus sẽ scrape
  address: 0.0.0.0:9090
  collect: {} # Cấu hình mặc định

# Cấu hình plugin Logs để hiển thị lỗi ra terminal
logs:
  # Mức độ log: debug, info, warn, error, dpanic, panic, fatal
  level: debug
  channels:
    default:
      # Xuất log ra Standard Error, sẽ hiển thị trong cửa sổ terminal của bạn
      output: "stderr"
      # Định dạng console dễ đọc, thay vì JSON
      formatter: "console"

# Định nghĩa các nhóm worker (server pools)
server:
  # Worker chuyên xử lý các lệnh RPC (ví dụ: reset workers)
  # Worker này sẽ được bảo mật bằng token.
  rpc-resetter:
    command: "php reset_worker.php"
    # Worker này không cần nhiều instance
    num_workers: 1

  # Worker chuyên xử lý các request HTTP
  http:
    command: "php worker.php"

  # Worker chuyên xử lý các yêu cầu proxy từ Centrifugo Server
  centrifugo:
    command: "php cli centrifugo:serve"
    num_workers: 1

# Cấu hình plugin HTTP
http:
  address: "0.0.0.0:8080"
  # Liên kết plugin này với nhóm worker 'http'
  workers:
    server: http
    pool:
      num_workers: 2 # Có thể điều chỉnh tùy theo tải

# Cấu hình plugin Centrifuge để giao tiếp với Centrifugo Server
centrifuge:
  # Địa chỉ mà RoadRunner sẽ lắng nghe các yêu cầu gRPC từ Centrifugo
  proxy_address: "tcp://127.0.0.1:10001"
  # Liên kết plugin này với nhóm worker 'centrifugo'
  workers:
    server: centrifugo

# Cấu hình plugin Reload (Hot-Reload) cho môi trường phát triển
reload:
  # Tần suất quét file thay đổi (ví dụ: 1 giây một lần)
  interval: 1s
  # Các đuôi file cần theo dõi. Thêm .env và .yml để reload khi cấu hình thay đổi.
  patterns: [".php", ".yml", ".env"]
  # Các thư mục cần theo dõi. "." nghĩa là toàn bộ thư mục dự án.
  dirs:
    - "."
  # Các thư mục cần bỏ qua để tối ưu hiệu năng.
  ignore:
    - "vendor"
    - "storage"
    - "bootstrap/cache"
  # Tên các service (worker pools) cần được reset khi có thay đổi.
  services:
    http: {} # Reset worker 'http'
