version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001, tcp://127.0.0.1:6002'

logs:
  level: debug
  channels:
    default:
      output: "stderr"
      formatter: "console"

metrics:
  address: '0.0.0.0:9090'
  collect: {}

kv:
  local:
    driver: memory
    config:
      interval: 60

reload:
  interval: 1s
  patterns: [".php", ".yml", ".env"]
  dirs:
    - "."
  ignore:
    - "vendor"
    - "storage"
    - "bootstrap/cache"
  services:
    http: {}

server:
  default:
    command: "php worker.php"
    num_workers: 1

  rpc-resetter:
    command: "php reset_worker.php"
    num_workers: 1

  http:
    command: "php worker.php"
    num_workers: 2
    supervisor:
      max_worker_memory: 100

  centrifugo:
    command: "php cli websocket:serve"
    num_workers: 1

http:
  address: '0.0.0.0:8080'
  middleware:
    - gzip
    - static
  static:
    dir: public
    forbid:
      - .php
      - .htaccess
  # Tham chiếu đến worker pool có tên 'http' đã định nghĩa ở trên.
  # Sử dụng cú pháp `pool` của RoadRunner v3.
  pool: http

centrifuge:
  proxy_address: "tcp://127.0.0.1:10001"
  # Tham chiếu đến worker pool 'centrifugo'. Sử dụng cú pháp v3.
  pool: centrifugo
