#!/usr/bin/env php
<?php

// cli
require __DIR__.'/vendor/autoload.php';

// Load .env
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

// 1. Bootstrap the application to get the container
$appKernel = new \Core\AppKernel();
$app = $appKernel->getApplication();

// 2. Create and run the Console Kernel
$consoleKernel = new Core\CLI\ConsoleKernel($app);

 $status = $consoleKernel->handle();

exit($status);
