# File này chứa các cấu hình GHI ĐÈ chỉ dành cho môi trường development.
# Docker Compose sẽ tự động merge file này với file docker-compose.yml chính.

services:
  app:
    volumes:
      - .:/app:cached
      - /app/vendor

  nginx:
    ports:
      - "${NGINX_HOST_PORT:-888}:80"

  

  centrifugo:
    ports:
      - "${CENTRIFUGO_HOST_PORT:-8000}:8000"

  phpmyadmin:
    ports:
      - "${PMA_HOST_PORT:-8080}:80"

volumes:
  bault-node-modules:
    driver: local
