# File này chứa các cấu hình GHI ĐÈ chỉ dành cho môi trường development.
# Docker Compose sẽ tự động merge file này với file docker-compose.yml chính.

services:
  app:
    # Đảm bảo container vite được khởi động trước container app
    depends_on:
      - vite
    volumes:
      - .:/app:cached
      - /app/vendor

  nginx:
    ports:
      - "${NGINX_HOST_PORT:-88}:80"

  vite:
    ports:
      - "${VITE_HOST_PORT:-5173}:5173"
    volumes:
      - .:/app:cached
      - bault-node-modules:/app/node_modules

  centrifugo:
    ports:
      - "${CENTRIFUGO_HOST_PORT:-8000}:8000"

  phpmyadmin:
    ports:
      - "${PMA_HOST_PORT:-8080}:80"

volumes:
  bault-node-modules:
    driver: local
