<?php

// This file is auto-generated by the 'config:cache' command.

return array (
  0 => 'App\\Providers\\AuthServiceProvider',
  1 => 'App\\Providers\\CacheServiceProvider',
  2 => 'App\\Providers\\ConfigServiceProvider',
  3 => 'App\\Providers\\DatabaseServiceProvider',
  4 => 'App\\Providers\\ConsoleServiceProvider',
  5 => 'App\\Providers\\EventServiceProvider',
  6 => 'App\\Providers\\ExceptionServiceProvider',
  7 => 'App\\Providers\\LoggingServiceProvider',
  8 => 'App\\Providers\\RouteServiceProvider',
  9 => 'App\\Providers\\QueueServiceProvider',
  10 => 'App\\Providers\\ValidationServiceProvider',
  11 => 'App\\Providers\\AppServiceProvider',
);
