<?php

namespace Core\Console\Commands;

use Core\AppKernel;
use Core\Console\Contracts\BaseCommand;

class ConfigCacheCommand extends BaseCommand
{
    public function __construct(private AppKernel $kernel) {
        parent::__construct();
    }

    public function signature(): string
    {
        return 'config:cache';
    }

    public function description(): string
    {
        return 'Create a service provider cache file for faster application bootstrapping.';
    }

    public function handle(): int
    {
        $this->comment('Caching Service Providers...');

        $cachePath = $this->app->getCachedProvidersPath();

        // Lấy danh sách tất cả provider từ AppKernel
        $providers = $this->kernel->getProvidersForCaching();

        $exported = var_export($providers, true);
        $content = "<?php\n\n// This file is auto-generated by the 'config:cache' command.\n\nreturn " . $exported . ";\n";

        // Đảm bảo thư mục cache tồn tại
        $cacheDir = dirname($cachePath);
        if (!is_dir($cacheDir)) {
            mkdir($cacheDir, 0777, true);
        }

        file_put_contents($cachePath, $content);
        $this->info('✔ Service providers cached successfully!');
        return 0;
    }
}